language: node_js
node_js:
  - "16"
services:
  - postgresql
env:
  - NODE_ENV=test
install:
  - npm install
before_script:
  - psql -c 'create database unit_test_db;' -U postgres
  - npx sequelize db:migrate --env test
deploy:
  provider: heroku
  app: lit-scrubland-41591
  on:
    repo: LinZH-1995/ECtest-test
    branch: main
  edge: true
  skip_cleanup: true
  run:
    - npx sequelize db:migrate
